# Site
repository: PeterLu030/PeterLu030.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yuan-Hsiang Lu
title: ECE Ph.D. @ Georgia Tech
email: yuan-hsiang.lu@gatech.edu
website: PeterLu030.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  PeterLu030
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0005-7222-2854

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yuan-Hsiang or you also call me Peter. I'm a a first-year Ph.D. student supervised by [Prof. Sung Kyu Lim](http://limsk.ece.gatech.edu) at [Georgia Tech Computer-aided Design Lab(GTCAD)](https://www.gtcad.gatech.edu). My research interests are in Machine Learning(ML) and Electronic Design Automation(EDA), and I’m currently working on topics related to GPU-accelerated routing.

content:
  - title: Publication # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - **Yuan-Hsiang Lu**, Chung-Yi Li, and Zih-Wei Lin. 2023. [**The Taiwan AI Labs Hakka ASR System for Formosa Speech Recognition Challenge 2023**](https://aclanthology.org/2023.rocling-1.53/). In Proceedings of the 35th Conference on Computational Linguistics and Speech Processing (ROCLING 2023), pages 403–408, Taipei City, Taiwan. The Association for Computational Linguistics and Chinese Language Processing (ACLCLP).

      - Cheng-Yun Hsieh, Hsin-Ying Tsai, **Yuan-Hsiang Lu**, and James Chien-Mo Li. 2023. [**Small Sampling Overhead Error Mitigation for Quantum Circuits**](https://ieeexplore.ieee.org/document/10304329). In IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems, vol. 43, no. 3, pp. 826-839, March 2024.

      - Chao-Chi Lan, Chuan-Chi Su, **Yuan-Hsiang Lu**, Yao-Wen Chang. **Robust Technology-Transferable Static IR Drop Prediction Based on Image-to-Image Machine Learning**. In Proceedings of 2025 30th Asia and South Pacific Design Automation Conference (ASP-DAC) (Accepted)


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institution of Technology
        caption: 2024 - Present
        sub_title: Ph.D. in Electrical and Computer Engineering
        description: | # this will include new lines to allow paragraphs
          - Graduate Research Assistant @ GTCAD

      - layout: left
        title: National Taiwan University
        caption: 2019 - 2024
        sub_title: B.S. in Electrical Engineering
        description: | # this will include new lines to allow paragraphs
          - GPA: 4.15/4.30 | Last two year: 4.19 / 4.30

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in ML and EDA some of my other interests and hobbies are:
      - Playing Board Game
      - Playing Video Game
      - Reading Novel
      # - Knitting
      # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      # Look at this cool image  
      # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
